### ISSUE TITLE
Question on reproducing results in the elbow pose task

### ISSUE THREAD

**Issue by Beanpow** [amathislab/lattice#1]
Hi, thanks for sharing your code. Recently, I am trying to reproduce your result in your paper. But I got different results. Could you give me some insights?

I didn't modify any code, just ran the following commands
* State-independent Lattice freq=1
```
docker run --rm --gpus all -it \ 
--mount type=bind,src="$(pwd)/src",target=/src \
--mount type=bind,src="$(pwd)/data",target=/data \ 
--mount type=bind,src="$(pwd)/output",target=/output \ 
albertochiappa/myo-cuda-pybullet \
python3 src/main_pose_elbow.py --use_lattice
```

* non-sde exploration
```
docker run --rm --gpus all -it \ 
--mount type=bind,src="$(pwd)/src",target=/src \
--mount type=bind,src="$(pwd)/data",target=/data \ 
--mount type=bind,src="$(pwd)/output",target=/output \ 
albertochiappa/myo-cuda-pybullet \
python3 src/main_pose_elbow.py
```

* State-dependent Lattice freq=1
```
docker run --rm --gpus all -it \ 
--mount type=bind,src="$(pwd)/src",target=/src \
--mount type=bind,src="$(pwd)/data",target=/data \ 
--mount type=bind,src="$(pwd)/output",target=/output \ 
albertochiappa/myo-cuda-pybullet \
python3 src/main_pose_elbow.py  --use_lattice --use_sde
```

* State-dependent Lattice freq=1 init_log_std=1
```
docker run --rm --gpus all -it \ 
--mount type=bind,src="$(pwd)/src",target=/src \
--mount type=bind,src="$(pwd)/data",target=/data \ 
--mount type=bind,src="$(pwd)/output",target=/output \ 
albertochiappa/myo-cuda-pybullet \
python3 src/main_pose_elbow.py  --use_lattice --use_sde --init_log_std=1
```

and here is the result I got.

![image](https://github.com/amathislab/lattice/assets/37178760/1b815326-6209-4689-9ce2-3790e334a8d7)

So, my question is:

1. Some commands in your Readme don't open the --use_sde flag, so should I open the flag if I want to reproduce the result in your paper?
2. The default args are different from your paper, which args I should use? such as the init_log_std in main_pose_elbow.py.

**Comment by albertochiappa** [comment]
Hi, thanks for trying out our code!

In the supplementary material of the paper you can find the detail of the hyperparameters used for every environment, you can take them from there. As you have also tested, Lattice with gSDE required higher initial standard deviation to work well in the elbow pose environment. We used multiple environments in parallel to speed up the training, you might want to try that.

Lattice without SDE was added after the publication of the paper, so we have not benchmarked it in the elbow pose environment. However, we have used for our solution of the [MyoChallenge 2023](https://github.com/amathislab/myochallenge-lattice). From your learning curves it seems like it's solving the task correctly!
